# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
